//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAuthService.StormpathRepository {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class StormpathConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static StormpathConfig defaultInstance = ((StormpathConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StormpathConfig())));
        
        public static StormpathConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4O3R44KMNZ8KVAI61L6Z2YTMT")]
        public string ApiKey {
            get {
                return ((string)(this["ApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hh2hXM4nSl9l7KU9LB+YfQpPySEY2mM0kZP4Da35mT4")]
        public string ApiKeySecret {
            get {
                return ((string)(this["ApiKeySecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.stormpath.com/v1/applications/52DzPnSxEfgbVQcgzdSn8D")]
        public string ApplicationUrl {
            get {
                return ((string)(this["ApplicationUrl"]));
            }
        }
    }
}
